name: Windows
on:
  push:
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: show path
      run: dir .
      shell: pwsh
    - name: build tdlib
      run: powershell ./script.ps1
      shell: pwsh
    - name: show build
      run: dir .
      shell: pwsh
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: td/tdlib/
    - name: test cd
      run: cd /;pwd;dir .
    
