name: Windows
on:
  push:
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: build tdlib
      run: $GITHUB_ACTION_PATH/script.ps1
      shell: pwsh
    - name: show build
      run: dir .
